
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shreyas Sudhakar
description: This is the personal website of Shreyas Sudhakar.
social:
    links:
      - https://www.linkedin.com/in/shreyassudhakar/
      - https://github.com/ssuds
google_site_verification: cymXx0S6wZsbhwYGKIY2WmjjeG5ppagjIRKrSv4m_sk
baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown
highlighter: rouge

sass:
  # loading path from site root
  # default to _sass
  # sass_dir: bower_components

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  # style: compressed

gems:
  - jekyll-seo-tag
